const button=document.querySelectorAll(".button");
const body=document.querySelector("body");
const heading=document.querySelector("#heading");
const title=document.querySelector("#title");
button.forEach((button)=>
{
    button.addEventListener("click",(e)=>
    {
        if(e.target.id==="grey")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;
            title.style.color=e.target.id;
        }
        if(e.target.id==="red")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;  
            title.style.color=e.target.id;      
        }
        if(e.target.id==="blue")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;
            title.style.color=e.target.id;
        }
        if(e.target.id==="yellow")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;  
            title.style.color=e.target.id;     
        }
        if(e.target.id==="green")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;
            title.style.color=e.target.id;
        }
        if(e.target.id==="purple")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;  
            title.style.color=e.target.id;     
        }
        if(e.target.id==="black")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;
            title.style.color=e.target.id;
        }
        if(e.target.id==="aqua")
        {
            body.style.background=e.target.id;
            heading.style.color=e.target.id;  
            title.style.color=e.target.id;     
        }
    })
})
